- name: Install apache httpd  (state=present is optional)
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - docker-compose
    - zip

- name: Remove "foo" package
  ansible.builtin.apt:
    name: zip
    state: absent

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://archive.canonical.com/ubuntu hardy partner
    state: present    

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://ftp-master.debian.org/keys/archive-key-6.0.asc
    state: present