---
plugin: aws_ec2
# Populate inventory with instances in these regions
regions:
  - ap-southeast-2
filters:
  tag:Project: jenkins
keyed_groups:
  - prefix: tag # prefix is 'tag_'
    key: tags['Role'] # the Name tag can be 'web' or 'redis'

    # so the groups are tag_web and tag_redis